### ISSUE TITLE
甲骨文云centos系统，安装后，启动失败，求助

### ISSUE THREAD

**Issue by star2k** [istoreos/istoreos-cloud#2]
![Snipaste_2022-11-09_19-52-52](https://user-images.githubusercontent.com/9582078/200823733-5c4e2cc7-7845-4f1f-abb7-9c449129fc49.png)
提示安装成功，启动后，看不到界面，提示如图，求助解决方法？
另外，卸载该云openwrt的命令是什么？

**Comment by jjm2473** [comment]
重装系统不就卸载了吗？

**Comment by jjm2473** [comment]
这个云openwrt启动以后是用dhcp获取ip地址的，如果你的云服务没提供dhcp，那就没法获取ip了

**Comment by star2k** [comment]
云服务器是有公网静态ip的

**Comment by jjm2473** [comment]
> 



> 云服务器是有公网静态ip的

腾讯云也有公网ip啊，但是虚拟机是有内部ip的，不是直接使用公网ip。内部ip是用dhcp获取
