### ISSUE TITLE
阿里云启动失败

### ISSUE THREAD

**Issue by 18657769868** [istoreos/istoreos-cloud#5]
![image](https://github.com/istoreos/istoreos-cloud/assets/22534813/29c17656-fab0-4737-b25c-53d5ab2191e6)

**Comment by jjm2473** [comment]
是不是没刷成功

**Comment by 18657769868** [comment]
阿里云控制台里再重启,运行正常了.但还是连不通.
VNC连上去, 命令行看 发现没自动获得IP, 手动设置ip 正常连通了

**Comment by jjm2473** [comment]
系统启动以后执行下`cat /tmp/sysinfo/board_name`看看

**Comment by jjm2473** [comment]
目前只有腾讯云会自动切换成DHCP客户端

**Comment by jjm2473** [comment]
相关代码 https://github.com/istoreos/istoreos/blob/fcdf68a1f6b0e89042b4808f48cc4bfdffca0f3c/target/linux/x86/base-files/etc/board.d/02_network#L49-L51
